### ISSUE TITLE
Associating parent tags

### ISSUE THREAD

**Issue by JamieMason** [bbc-sport/ShouldIT#15]
**Steps**

+ Create a feature file with tag `generic`.
+ Create a feature file with tags `generic` and `specialisation-one`.
+ Create another feature file with tags `generic` and `specialisation-two`.
+ Run `shouldit --tags=generic`

**Expected**

See results for all three feature files.

**Actual**

See results for feature file containing only the `generic` tag.

**Comment by mackstar** [comment]
If you would like multiple tags. They are entered in the following manor:

```
> @tag1, @tag2
```

I will update the documentation in a week or so!

**Comment by JamieMason** [comment]
Thanks @mackstar!

**Comment by JamieMason** [comment]
Ah, there's an error now when running the following in 0.4.3 that seems to happen regardless of whether a match was found for the tag names.

```shell
shouldit --watch --serve --tags=generic
```

    /usr/local/lib/node_modules/shouldit/lib/markdownParser.js:108
            needles.forEach(function (needle) {
                    ^
    TypeError: undefined is not a function
        at containsTags (/usr/local/lib/node_modules/shouldit/lib/markdownParser.js:108:17)
        at handleLine (/usr/local/lib/node_modules/shouldit/lib/markdownParser.js:122:41)
        at /usr/local/lib/node_modules/shouldit/lib/markdownParser.js:99:9
        at /usr/local/lib/node_modules/shouldit/node_modules/line-reader/lib/line_reader.js:152:17
        at getLine (/usr/local/lib/node_modules/shouldit/node_modules/line-reader/lib/line_reader.js:74:9)
        at LineReader.nextLine (/usr/local/lib/node_modules/shouldit/node_modules/line-reader/lib/line_reader.js:93:9)
        at Immediate.readNext [as _onImmediate] (/usr/local/lib/node_modules/shouldit/node_modules/line-reader/lib/line_reader.js:146:16)
        at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by JamieMason** [comment]
on line 108 of markdownParser `needles` is a `String`, but I think you're expecting an `Array`.

**Comment by mackstar** [comment]
Bummer - looks like that fix was a bit premature. Will look into it probably tomorrow night. Soz... Probably the test was not quite accurate...

**Comment by mackstar** [comment]
Fixed...
